name: ga_retail_project
version: 1.0.0
config-version: 2
profile: ga_retail_project
model-paths: ["models"]
target-path: "target"
clean-targets: ["target", "dbt_packages"]

models:
  ga_retail_project:
    staging:
      +schema: stg # all models in models/staging → BigQuery dataset "stg"
      +materialized: view
    intermediate:
      +schema: int # all models in models/intermediate → dataset "int"
      +materialized: view
    mart:
      +schema: mart # all models in models/mart → dataset "mart"
      +materialized: table
