version: 2

sources:
  - name: ext
    description: "External ingested datasets for enrichment (fx rates, country mapping)."
    database: e2e-dbt-project
    schema: ext

    tables:
      - name: country_currency
        description: "Mapping of countries to local currencies."
        columns:
          - name: country
            description: "Country name."
            tests:
              - not_null
          - name: currency
            description: "ISO currency code (e.g., USD, EUR)."
            tests:
              - not_null

      - name: fx_rates
        description: "Foreign exchange rates to USD (USD per 1 currency)."
        # IMPORTANT: cast DATE -> TIMESTAMP for freshness checks
        loaded_at_field: "TIMESTAMP(rate_date)"
        freshness:
          warn_after: { count: 1, period: day }
          error_after: { count: 2, period: day }
        columns:
          - name: rate_date
            description: "Date of FX rate."
            tests:
              - not_null
          - name: currency
            description: "ISO currency code."
            tests:
              - not_null
          - name: rate_to_usd
            description: "Conversion rate: USD per 1 unit of currency."
            tests:
              - not_null
